# Generated by Django 4.2.1 on 2023-10-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('country_name', models.CharField(db_column='country_name', max_length=120, null=True, unique=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
