# Generated by Django 4.2.1 on 2023-11-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('state_name', models.CharField(db_column='state_name', max_length=120, null=True, unique=True)),
                ('country_id', models.ForeignKey(db_column='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='countryapp.country')),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
